// Code generated by goderive DO NOT EDIT.

package db

import (
	"anekdotas"
)

// deriveFmapRecordToModel returns a list where each element of the input list has been morphed by the input function.
func deriveFmapRecordToModel(f func(*QuestionRecord) *anekdotas.Question, list []*QuestionRecord) []*anekdotas.Question {
	out := make([]*anekdotas.Question, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}
