// Code generated by goderive DO NOT EDIT.

package handlers

import (
	"anekdotas"
	"anekdotas/internal/api"
)

// deriveFmapCategories returns a list where each element of the input list has been morphed by the input function.
func deriveFmapCategories(f func(*anekdotas.Category) *api.Category, list []*anekdotas.Category) []*api.Category {
	out := make([]*api.Category, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}

// deriveFmapQuestions returns a list where each element of the input list has been morphed by the input function.
func deriveFmapQuestions(f func(*anekdotas.Question) *api.Question, list []*anekdotas.Question) []*api.Question {
	out := make([]*api.Question, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}

// deriveFmapTopics returns a list where each element of the input list has been morphed by the input function.
func deriveFmapTopics(f func(*anekdotas.Topic) *api.Topic, list []*anekdotas.Topic) []*api.Topic {
	out := make([]*api.Topic, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}
